version: '3'

services:
  app:
    container_name: echo-cbot-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1323:1323"
    restart: unless-stopped
    depends_on:
      - db
    environment:
      MONGO_HOST: mongodb://db:27017
      MONGO_DB_NAME: echo-cbot

  db:
    container_name: echo-cbot-db
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27018:27017"